require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/matchup_posts", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # MatchupPost. As you add validations to MatchupPost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MatchupPost.create! valid_attributes
      get matchup_posts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      matchup_post = MatchupPost.create! valid_attributes
      get matchup_post_url(matchup_post)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_matchup_post_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      matchup_post = MatchupPost.create! valid_attributes
      get edit_matchup_post_url(matchup_post)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MatchupPost" do
        expect {
          post matchup_posts_url, params: { matchup_post: valid_attributes }
        }.to change(MatchupPost, :count).by(1)
      end

      it "redirects to the created matchup_post" do
        post matchup_posts_url, params: { matchup_post: valid_attributes }
        expect(response).to redirect_to(matchup_post_url(MatchupPost.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MatchupPost" do
        expect {
          post matchup_posts_url, params: { matchup_post: invalid_attributes }
        }.to change(MatchupPost, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post matchup_posts_url, params: { matchup_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested matchup_post" do
        matchup_post = MatchupPost.create! valid_attributes
        patch matchup_post_url(matchup_post), params: { matchup_post: new_attributes }
        matchup_post.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the matchup_post" do
        matchup_post = MatchupPost.create! valid_attributes
        patch matchup_post_url(matchup_post), params: { matchup_post: new_attributes }
        matchup_post.reload
        expect(response).to redirect_to(matchup_post_url(matchup_post))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        matchup_post = MatchupPost.create! valid_attributes
        patch matchup_post_url(matchup_post), params: { matchup_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested matchup_post" do
      matchup_post = MatchupPost.create! valid_attributes
      expect {
        delete matchup_post_url(matchup_post)
      }.to change(MatchupPost, :count).by(-1)
    end

    it "redirects to the matchup_posts list" do
      matchup_post = MatchupPost.create! valid_attributes
      delete matchup_post_url(matchup_post)
      expect(response).to redirect_to(matchup_posts_url)
    end
  end
end
